RB-553: Fix canAdd not always working as expected
RainBirdAi/chirpy-ui pull request #40
Opened 2016-11-23 15:58 UTC by LawrieR

2016-11-24 12:22 UTC, craig-rainbird commented on public/chirpy.js
> +            if (checkInputAndHighlightButtons({canAdd:true, allowUnkown:false}) && d3.event.key === 'Enter') {
Typo allowUnkown?

2016-11-24 12:25 UTC, craig-rainbird requested changes
Typo allowUnkown?

2016-11-24 12:25 UTC, craig-rainbird commented on public/chirpy.js
> +            if (checkInputAndHighlightButtons({canAdd:true, allowUnkown:false}) && d3.event.key === 'Enter') {
Typo allowUnkown?

2016-11-29 10:00 UTC, nroberts1 approved these changes

2016-11-29 10:01 UTC, merged